#################################################################
# Config for A2A Planner Agent that can define a plan
# and coordinate execution over multiple A2A agent
#################################################################

#################################################################
# General parameters
#################################################################
agent_planner_name="planner"
agent_planner_host="127.0.0.1"
agent_planner_http_port="9080"
# future use. Websocket is not supported
agent_planner_ws_port="9081"

#################################################################
# Purpose and high level skills
# The agent will use the A2A protocol for his interactions
#################################################################
agent_planner_system_prompt="You are a helpful planner agent. You define a plan and coordinate execution over other connected agents"

#################################################################
# Define her the url of openai compatible endpoint 
# as well as the model to use
#################################################################
#agent_planner_model_id="qwen/qwen3-32b"
#agent_planner_llm_url="https://api.groq.com/openai/v1/chat/completions"
agent_planner_model_id="gemini-2.0-flash"
agent_planner_llm_url="https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"

#################################################################
# Future use : It would make sense to have a discovery service
# so that planner agent can dynamically discover agents to
# connect to
#################################################################
agent_planner_discovery_url="http://127.0.0.1:4000/"

#################################################################
# Series of agents to which planner agent is connected to
# once he has defined a plan, he will coordinate execution
# accross the A2A agents he is connected to
# todo : Add prefered or default agent
#################################################################
[[agent_planner_agents_references]]
name = "agent_search"
url = "http://127.0.0.1:8080"
is_default=true

#[[agent_planner_agents_references]]
#name = "weather_agent"
#url = "http://127.0.0.1:8082"

#[[agent_planner_agents_references]]
#name = "customer_agent"
#url = "http://127.0.0.1:8084"